services:
  redis:
    image: redis:8.6.2
    container_name: openpoker-redis
    ports:
      - "6379:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -u redis://${REDIS_USER:-default}:${REDIS_PASSWORD}@redis:6379 ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:18.3
    container_name: openpoker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openpoker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  server:
    image: openpoker-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/openpoker
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: ${REDIS_USER:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-postgres}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
