/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/game/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GameService_auth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GameService_getTables"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TableService_connect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionOptions: components["schemas"]["ActionOptionsFold"] | components["schemas"]["ActionOptionsCheck"] | components["schemas"]["ActionOptionsBet"] | components["schemas"]["ActionOptionsRaise"] | components["schemas"]["ActionOptionsCall"] | components["schemas"]["ActionOptionsPostSmallBlind"] | components["schemas"]["ActionOptionsPostBigBlind"];
        ActionOptionsBet: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Bet";
            value: components["schemas"]["BetOption"];
        };
        ActionOptionsCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Call";
            value: components["schemas"]["CallOption"];
        };
        ActionOptionsCheck: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Check";
            value: components["schemas"]["CheckOption"];
        };
        ActionOptionsFold: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Fold";
            value: components["schemas"]["FoldOption"];
        };
        ActionOptionsPostBigBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PostBigBlind";
            value: components["schemas"]["PostBigBlindOption"];
        };
        ActionOptionsPostSmallBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PostSmallBlind";
            value: components["schemas"]["PostSmallBlindOption"];
        };
        ActionOptionsRaise: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Raise";
            value: components["schemas"]["RaiseOption"];
        };
        AuthRequest: {
            name: string;
        };
        AuthResponse: {
            token: string;
        };
        Bet: {
            /** @enum {string} */
            type: "Bet";
            /** Format: double */
            amount: number;
        };
        BetOption: {
            /** @enum {string} */
            type: "BetOption";
            /** Format: double */
            minAmount: number;
            /** Format: double */
            maxAmount?: number;
        };
        CallOption: {
            /** @enum {string} */
            type: "CallOption";
            /** Format: double */
            amount: number;
        };
        Check: {
            /** @enum {string} */
            type: "Check";
        };
        CheckOption: {
            /** @enum {string} */
            type: "CheckOption";
        };
        CommunityCardDealt: {
            /** @enum {string} */
            type: "CommunityCardDealtEvent";
            cards: string[];
        };
        Fold: {
            /** @enum {string} */
            type: "Fold";
        };
        FoldOption: {
            /** @enum {string} */
            type: "FoldOption";
        };
        GetTablesRequest: Record<string, never>;
        HandEvent: components["schemas"]["HandEventPlayerSatDown"] | components["schemas"]["HandEventPlayerStoodUp"] | components["schemas"]["HandEventHandStarted"] | components["schemas"]["HandEventRoundStarted"] | components["schemas"]["HandEventCommunityCardDealt"] | components["schemas"]["HandEventPrivateCardDealt"] | components["schemas"]["HandEventHandFinished"] | components["schemas"]["HandEventPlayerActionRequested"] | components["schemas"]["HandEventPlayerPostedSmallBlind"] | components["schemas"]["HandEventPlayerPostedBigBlind"] | components["schemas"]["HandEventPlayerPostedAnte"] | components["schemas"]["HandEventPlayerFolded"] | components["schemas"]["HandEventPlayerChecked"] | components["schemas"]["HandEventPlayerBet"] | components["schemas"]["HandEventPlayerRaised"] | components["schemas"]["HandEventPlayerCalled"] | components["schemas"]["HandEventPlayerShowedCard"];
        HandEventCommunityCardDealt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CommunityCardDealt";
            value: components["schemas"]["CommunityCardDealt"];
        };
        HandEventHandFinished: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "HandFinished";
            value: components["schemas"]["HandFinished"];
        };
        HandEventHandStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "HandStarted";
            value: components["schemas"]["HandStarted"];
        };
        HandEventPlayerActionRequested: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerActionRequested";
            value: components["schemas"]["PlayerActionRequested"];
        };
        HandEventPlayerBet: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerBet";
            value: components["schemas"]["PlayerBet"];
        };
        HandEventPlayerCalled: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerCalled";
            value: components["schemas"]["PlayerCalled"];
        };
        HandEventPlayerChecked: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerChecked";
            value: components["schemas"]["PlayerChecked"];
        };
        HandEventPlayerFolded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerFolded";
            value: components["schemas"]["PlayerFolded"];
        };
        HandEventPlayerPostedAnte: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerPostedAnte";
            value: components["schemas"]["PlayerPostedAnte"];
        };
        HandEventPlayerPostedBigBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerPostedBigBlind";
            value: components["schemas"]["PlayerPostedBigBlind"];
        };
        HandEventPlayerPostedSmallBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerPostedSmallBlind";
            value: components["schemas"]["PlayerPostedSmallBlind"];
        };
        HandEventPlayerRaised: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerRaised";
            value: components["schemas"]["PlayerRaised"];
        };
        HandEventPlayerSatDown: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerSatDown";
            value: components["schemas"]["PlayerSatDown"];
        };
        HandEventPlayerShowedCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerShowedCard";
            value: components["schemas"]["PlayerShowedCard"];
        };
        HandEventPlayerStoodUp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PlayerStoodUp";
            value: components["schemas"]["PlayerStoodUp"];
        };
        HandEventPrivateCardDealt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PrivateCardDealt";
            value: components["schemas"]["PrivateCardDealt"];
        };
        HandEventRoundStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "RoundStarted";
            value: components["schemas"]["RoundStarted"];
        };
        HandFinished: {
            /** @enum {string} */
            type: "HandFinished";
            winners: number[];
        };
        HandStarted: {
            /** @enum {string} */
            type: "HandStartedEvent";
            /** Format: int32 */
            dealerButton: number;
        };
        PlayerAction: components["schemas"]["PlayerActionFold"] | components["schemas"]["PlayerActionCheck"] | components["schemas"]["PlayerActionBet"] | components["schemas"]["PlayerActionRaise"] | components["schemas"]["PlayerActionPostSmallBlind"] | components["schemas"]["PlayerActionPostBigBlind"] | components["schemas"]["PlayerActionStandUp"] | components["schemas"]["PlayerActionSitDown"];
        PlayerActionBet: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Bet";
            value: components["schemas"]["Bet"];
        };
        PlayerActionCheck: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Check";
            value: components["schemas"]["Check"];
        };
        PlayerActionFold: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Fold";
            value: components["schemas"]["Fold"];
        };
        PlayerActionPostBigBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PostBigBlind";
            value: components["schemas"]["PostBigBlind"];
        };
        PlayerActionPostSmallBlind: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "PostSmallBlind";
            value: components["schemas"]["PostSmallBlind"];
        };
        PlayerActionRaise: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "Raise";
            value: components["schemas"]["Raise"];
        };
        PlayerActionRequested: {
            /** @enum {string} */
            type: "PlayerActionRequested";
            /** Format: int32 */
            playerId: number;
            actionOptions: components["schemas"]["ActionOptions"][];
        };
        PlayerActionSitDown: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "SitDown";
            value: components["schemas"]["SitDown"];
        };
        PlayerActionStandUp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "StandUp";
            value: components["schemas"]["StandUp"];
        };
        PlayerBet: {
            /** @enum {string} */
            type: "PlayerBet";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerCalled: {
            /** @enum {string} */
            type: "PlayerCalled";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerChecked: {
            /** @enum {string} */
            type: "PlayerChecked";
            /** Format: int32 */
            playerId: number;
        };
        PlayerFolded: {
            /** @enum {string} */
            type: "PlayerFolded";
            /** Format: int32 */
            playerId: number;
        };
        PlayerPostedAnte: {
            /** @enum {string} */
            type: "PlayerPostedAnte";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerPostedBigBlind: {
            /** @enum {string} */
            type: "PlayerPostedBigBlind";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerPostedSmallBlind: {
            /** @enum {string} */
            type: "PlayerPostedSmallBlind";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerRaised: {
            /** @enum {string} */
            type: "PlayerRaised";
            /** Format: int32 */
            playerId: number;
            /** Format: double */
            amount: number;
            isAllIn: boolean;
        };
        PlayerSatDown: {
            /** @enum {string} */
            type: "PlayerSatDownEvent";
            /** Format: int32 */
            playerId: number;
            /** Format: int32 */
            seat: number;
        };
        PlayerShowedCard: {
            /** @enum {string} */
            type: "PlayerShowedCard";
            cards: string[];
        };
        PlayerStoodUp: {
            /** @enum {string} */
            type: "PlayerStoodUpEvent";
            /** Format: int32 */
            playerId: number;
        };
        PostBigBlind: {
            /** @enum {string} */
            type: "PostBigBlind";
            /** Format: double */
            amount: number;
        };
        PostBigBlindOption: {
            /** @enum {string} */
            type: "PostBigBlindOption";
            /** Format: double */
            amount: number;
        };
        PostSmallBlind: {
            /** @enum {string} */
            type: "PostSmallBlind";
            /** Format: double */
            amount: number;
        };
        PostSmallBlindOption: {
            /** @enum {string} */
            type: "PostSmallBlindOption";
            /** Format: double */
            amount: number;
        };
        PrivateCardDealt: {
            /** @enum {string} */
            type: "PrivateCardDealtEvent";
            /** Format: int32 */
            playerId: number;
            cards: string[];
        };
        Raise: {
            /** @enum {string} */
            type: "Raise";
            /** Format: double */
            amount: number;
        };
        RaiseOption: {
            /** @enum {string} */
            type: "RaiseOption";
            /** Format: double */
            minAmount: number;
            /** Format: double */
            maxAmount?: number;
        };
        RoundStarted: {
            /** @enum {string} */
            type: "RoundStartedEvent";
            street: string;
        };
        SitDown: {
            /** @enum {string} */
            type: "Check";
        };
        StandUp: {
            /** @enum {string} */
            type: "Check";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GameService_auth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    GameService_getTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTablesRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TableService_connect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerAction"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandEvent"];
                };
            };
        };
    };
}
