%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.7

-ifndef(gleam_gpb).
-define(gleam_gpb, true).

-define(gleam_gpb_gpb_version, "4.21.7").


-ifndef('OPENPOKER.V1.TABLEEVENT.DEALTCARDS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.DEALTCARDS_PB_H', true).
-record('openpoker.v1.TableEvent.DealtCards',
        {player_id = []         :: unicode:chardata() | undefined, % = 1, optional
         card_string = []       :: [unicode:chardata()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.MUCKSCARDS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.MUCKSCARDS_PB_H', true).
-record('openpoker.v1.TableEvent.MucksCards',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.SHOWSCARDS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.SHOWSCARDS_PB_H', true).
-record('openpoker.v1.TableEvent.ShowsCards',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         card_string = []       :: [unicode:chardata()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTANTE_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTANTE_PB_H', true).
-record('openpoker.v1.TableEvent.PostAnte',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTSMALLBLIND_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTSMALLBLIND_PB_H', true).
-record('openpoker.v1.TableEvent.PostSmallBlind',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTBIGBLIND_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTBIGBLIND_PB_H', true).
-record('openpoker.v1.TableEvent.PostBigBlind',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTSTRADDLE_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTSTRADDLE_PB_H', true).
-record('openpoker.v1.TableEvent.PostStraddle',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTDEADBLIND_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTDEADBLIND_PB_H', true).
-record('openpoker.v1.TableEvent.PostDeadBlind',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.POSTEXTRABLIND_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.POSTEXTRABLIND_PB_H', true).
-record('openpoker.v1.TableEvent.PostExtraBlind',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.FOLD_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.FOLD_PB_H', true).
-record('openpoker.v1.TableEvent.Fold',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.CHECK_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.CHECK_PB_H', true).
-record('openpoker.v1.TableEvent.Check',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.BET_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.BET_PB_H', true).
-record('openpoker.v1.TableEvent.Bet',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.RAISE_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.RAISE_PB_H', true).
-record('openpoker.v1.TableEvent.Raise',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         is_allin = false       :: boolean() | 0 | 1 | undefined % = 3, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.CALL_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.CALL_PB_H', true).
-record('openpoker.v1.TableEvent.Call',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.ADDEDCHIPS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.ADDEDCHIPS_PB_H', true).
-record('openpoker.v1.TableEvent.AddedChips',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.SITSDOWN_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.SITSDOWN_PB_H', true).
-record('openpoker.v1.TableEvent.SitsDown',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.STANDSUP_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.STANDSUP_PB_H', true).
-record('openpoker.v1.TableEvent.StandsUp',
        {player_id = 0          :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.ADDTOPOT_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.ADDTOPOT_PB_H', true).
-record('openpoker.v1.TableEvent.AddToPot',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.REQUESTPLAYERACTION_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.REQUESTPLAYERACTION_PB_H', true).
-record('openpoker.v1.TableEvent.RequestPlayerAction',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.DEALTABLECARDS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.DEALTABLECARDS_PB_H', true).
-record('openpoker.v1.TableEvent.DealTableCards',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT.DEALPRIVATECARDS_PB_H').
-define('OPENPOKER.V1.TABLEEVENT.DEALPRIVATECARDS_PB_H', true).
-record('openpoker.v1.TableEvent.DealPrivateCards',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEEVENT_PB_H').
-define('OPENPOKER.V1.TABLEEVENT_PB_H', true).
-record('openpoker.v1.TableEvent',
        {kind                   :: {dealt_cards, gleam_gpb:'openpoker.v1.TableEvent.DealtCards'()} | {mucks_cards, gleam_gpb:'openpoker.v1.TableEvent.MucksCards'()} | {shows_cards, gleam_gpb:'openpoker.v1.TableEvent.ShowsCards'()} | {post_ante, gleam_gpb:'openpoker.v1.TableEvent.PostAnte'()} | {post_small_blind, gleam_gpb:'openpoker.v1.TableEvent.PostSmallBlind'()} | {post_big_blind, gleam_gpb:'openpoker.v1.TableEvent.PostBigBlind'()} | {post_straddle, gleam_gpb:'openpoker.v1.TableEvent.PostStraddle'()} | {post_dead_blind, gleam_gpb:'openpoker.v1.TableEvent.PostDeadBlind'()} | {post_extra_blind, gleam_gpb:'openpoker.v1.TableEvent.PostExtraBlind'()} | {fold, gleam_gpb:'openpoker.v1.TableEvent.Fold'()} | {check, gleam_gpb:'openpoker.v1.TableEvent.Check'()} | {bet, gleam_gpb:'openpoker.v1.TableEvent.Bet'()} | {raise, gleam_gpb:'openpoker.v1.TableEvent.Raise'()} | {call, gleam_gpb:'openpoker.v1.TableEvent.Call'()} | {added_chips, gleam_gpb:'openpoker.v1.TableEvent.AddedChips'()} | {sits_down, gleam_gpb:'openpoker.v1.TableEvent.SitsDown'()} | {stands_up, gleam_gpb:'openpoker.v1.TableEvent.StandsUp'()} | {add_to_pot, gleam_gpb:'openpoker.v1.TableEvent.AddToPot'()} | {requested_player_action, gleam_gpb:'openpoker.v1.TableEvent.RequestPlayerAction'()} | {dealt_table_cards, gleam_gpb:'openpoker.v1.TableEvent.DealTableCards'()} | {dealt_private_cards, gleam_gpb:'openpoker.v1.TableEvent.DealPrivateCards'()} | undefined % oneof
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTANTE_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTANTE_PB_H', true).
-record('openpoker.v1.TableAction.PostAnte',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTSMALLBLIND_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTSMALLBLIND_PB_H', true).
-record('openpoker.v1.TableAction.PostSmallBlind',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTBIGBLIND_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTBIGBLIND_PB_H', true).
-record('openpoker.v1.TableAction.PostBigBlind',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTSTRADDLE_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTSTRADDLE_PB_H', true).
-record('openpoker.v1.TableAction.PostStraddle',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTDEADBLIND_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTDEADBLIND_PB_H', true).
-record('openpoker.v1.TableAction.PostDeadBlind',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.POSTEXTRABLIND_PB_H').
-define('OPENPOKER.V1.TABLEACTION.POSTEXTRABLIND_PB_H', true).
-record('openpoker.v1.TableAction.PostExtraBlind',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.FOLD_PB_H').
-define('OPENPOKER.V1.TABLEACTION.FOLD_PB_H', true).
-record('openpoker.v1.TableAction.Fold',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.CHECK_PB_H').
-define('OPENPOKER.V1.TABLEACTION.CHECK_PB_H', true).
-record('openpoker.v1.TableAction.Check',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.BET_PB_H').
-define('OPENPOKER.V1.TABLEACTION.BET_PB_H', true).
-record('openpoker.v1.TableAction.Bet',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.RAISE_PB_H').
-define('OPENPOKER.V1.TABLEACTION.RAISE_PB_H', true).
-record('openpoker.v1.TableAction.Raise',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.CALL_PB_H').
-define('OPENPOKER.V1.TABLEACTION.CALL_PB_H', true).
-record('openpoker.v1.TableAction.Call',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.MUCKCARDS_PB_H').
-define('OPENPOKER.V1.TABLEACTION.MUCKCARDS_PB_H', true).
-record('openpoker.v1.TableAction.MuckCards',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.SHOWCARDS_PB_H').
-define('OPENPOKER.V1.TABLEACTION.SHOWCARDS_PB_H', true).
-record('openpoker.v1.TableAction.ShowCards',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION.ADDCHIPS_PB_H').
-define('OPENPOKER.V1.TABLEACTION.ADDCHIPS_PB_H', true).
-record('openpoker.v1.TableAction.AddChips',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.TABLEACTION_PB_H').
-define('OPENPOKER.V1.TABLEACTION_PB_H', true).
-record('openpoker.v1.TableAction',
        {kind                   :: {mucks_cards, gleam_gpb:'openpoker.v1.TableAction.MuckCards'()} | {shows_cards, gleam_gpb:'openpoker.v1.TableAction.ShowCards'()} | {post_ante, gleam_gpb:'openpoker.v1.TableAction.PostAnte'()} | {post_small_blind, gleam_gpb:'openpoker.v1.TableAction.PostSmallBlind'()} | {post_big_blind, gleam_gpb:'openpoker.v1.TableAction.PostBigBlind'()} | {post_straddle, gleam_gpb:'openpoker.v1.TableAction.PostStraddle'()} | {post_dead_blind, gleam_gpb:'openpoker.v1.TableAction.PostDeadBlind'()} | {post_extra_blind, gleam_gpb:'openpoker.v1.TableAction.PostExtraBlind'()} | {fold, gleam_gpb:'openpoker.v1.TableAction.Fold'()} | {check, gleam_gpb:'openpoker.v1.TableAction.Check'()} | {bet, gleam_gpb:'openpoker.v1.TableAction.Bet'()} | {raise, gleam_gpb:'openpoker.v1.TableAction.Raise'()} | {call, gleam_gpb:'openpoker.v1.TableAction.Call'()} | {added_chips, gleam_gpb:'openpoker.v1.TableAction.AddChips'()} | undefined % oneof
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTSMALLBLIND_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTSMALLBLIND_PB_H', true).
-record('openpoker.v1.RequestedActionOption.PostSmallBlind',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTBIGBLIND_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTBIGBLIND_PB_H', true).
-record('openpoker.v1.RequestedActionOption.PostBigBlind',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTSTRADDLE_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTSTRADDLE_PB_H', true).
-record('openpoker.v1.RequestedActionOption.PostStraddle',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTDEADBLIND_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTDEADBLIND_PB_H', true).
-record('openpoker.v1.RequestedActionOption.PostDeadBlind',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTEXTRABLIND_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.POSTEXTRABLIND_PB_H', true).
-record('openpoker.v1.RequestedActionOption.PostExtraBlind',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.FOLD_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.FOLD_PB_H', true).
-record('openpoker.v1.RequestedActionOption.Fold',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.BET_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.BET_PB_H', true).
-record('openpoker.v1.RequestedActionOption.Bet',
        {min_amount = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1, optional
         max_amount = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.CHECK_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.CHECK_PB_H', true).
-record('openpoker.v1.RequestedActionOption.Check',
        {
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.RAISE_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.RAISE_PB_H', true).
-record('openpoker.v1.RequestedActionOption.Raise',
        {min_amount = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1, optional
         max_amount = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION.CALL_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION.CALL_PB_H', true).
-record('openpoker.v1.RequestedActionOption.Call',
        {amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 1, optional
        }).
-endif.

-ifndef('OPENPOKER.V1.REQUESTEDACTIONOPTION_PB_H').
-define('OPENPOKER.V1.REQUESTEDACTIONOPTION_PB_H', true).
-record('openpoker.v1.RequestedActionOption',
        {kind                   :: {post_small_blind, gleam_gpb:'openpoker.v1.RequestedActionOption.PostSmallBlind'()} | {post_big_blind, gleam_gpb:'openpoker.v1.RequestedActionOption.PostBigBlind'()} | {post_straddle, gleam_gpb:'openpoker.v1.RequestedActionOption.PostStraddle'()} | {post_dead_blind, gleam_gpb:'openpoker.v1.RequestedActionOption.PostDeadBlind'()} | {post_extra_blind, gleam_gpb:'openpoker.v1.RequestedActionOption.PostExtraBlind'()} | {fold, gleam_gpb:'openpoker.v1.RequestedActionOption.Fold'()} | {check, gleam_gpb:'openpoker.v1.RequestedActionOption.Check'()} | {bet, gleam_gpb:'openpoker.v1.RequestedActionOption.Bet'()} | {raise, gleam_gpb:'openpoker.v1.RequestedActionOption.Raise'()} | {call, gleam_gpb:'openpoker.v1.RequestedActionOption.Call'()} | undefined % oneof
        }).
-endif.

-ifndef('OPENPOKER.V1.POT_PB_H').
-define('OPENPOKER.V1.POT_PB_H', true).
-record('openpoker.v1.Pot',
        {number = 0             :: integer() | undefined, % = 1, optional, 32 bits
         amount = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         rake = 0.0             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3, optional
         player_wins = []       :: [gleam_gpb:'openpoker.v1.PlayerWin'()] | undefined % = 4, repeated
        }).
-endif.

-ifndef('OPENPOKER.V1.PLAYERWIN_PB_H').
-define('OPENPOKER.V1.PLAYERWIN_PB_H', true).
-record('openpoker.v1.PlayerWin',
        {player_id = 0          :: integer() | undefined, % = 1, optional, 32 bits
         win_amount = 0.0       :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         contributed_rake = 0.0 :: float() | integer() | infinity | '-infinity' | nan | undefined % = 3, optional
        }).
-endif.

-endif.
